"""
(c) 2019-2020 Kajetan Chrapkiewicz.
Copywright: Ask for permission writing to k.chrapkiewicz17@imperial.ac.uk.

"""
import numpy as np
import matplotlib.pyplot as plt
from autologging import logged, traced

from fullwavepy.generic.parse import kw, del_kw, exten, strip
from fullwavepy.generic.system import bash, exists
from fullwavepy.ioapi.generic import CsvFile
from fullwavepy.project.files.generic import TextProjFile



@traced
@logged
class HedFile(TextProjFile):
  """
  ASCII version of the idx SEG-Y metadata 
  index files for QC.
  
  Notes
  -----
  Whether or not it is generated by SegyPrep
  depends on the 'text' parameter in SegyPrep.key.
  
  """
  def __init__(self, suffix, proj, path, **kwargs):
    self.name = proj.name + '-' + suffix + '.hed'
    self.fname = path + self.name
    super().__init__(proj, path, **kwargs)


# -------------------------------------------------------------------------------


@traced
@logged
class ObsHedFile(HedFile):
  def __init__(self, proj, path, **kwargs):
    suffix = 'Observed'
    super().__init__(suffix, proj, path, **kwargs)

# -------------------------------------------------------------------------------



